

calculator_add:
    path: /add/{param1}/{param2}
    defaults: { _controller: AppBundle:Calculator:add }
    methods: [GET]
    requirements:
        param1: '\d+'
        param2: '\d+'

calculator_subtract:
    path: /subtract/
    defaults: { _controller: AppBundle:Calculator:subtract }


calculator_multiply:
    path: /multiply
    defaults: { _controller: AppBundle:Calculator:multiply }
    methods: [POST]

calculator_divide:
    path: /divide/{param1}
    defaults: { _controller: AppBundle:Calculator:divide }
    methods: [GET]
